import bash from "highlight.js/lib/languages/bash";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import csharp from "highlight.js/lib/languages/csharp";
import css from "highlight.js/lib/languages/css";
import dart from "highlight.js/lib/languages/dart";
import diff from "highlight.js/lib/languages/diff";
import go from "highlight.js/lib/languages/go";
import graphql from "highlight.js/lib/languages/graphql";
import ini from "highlight.js/lib/languages/ini";
import java from "highlight.js/lib/languages/java";
import javascript from "highlight.js/lib/languages/javascript";
import json from "highlight.js/lib/languages/json";
import kotlin from "highlight.js/lib/languages/kotlin";
import less from "highlight.js/lib/languages/less";
import lua from "highlight.js/lib/languages/lua";
import makefile from "highlight.js/lib/languages/makefile";
import markdown from "highlight.js/lib/languages/markdown";
import objectivec from "highlight.js/lib/languages/objectivec";
import perl from "highlight.js/lib/languages/perl";
import php from "highlight.js/lib/languages/php";
import plainText from "highlight.js/lib/languages/plaintext";
import python from "highlight.js/lib/languages/python";
import r from "highlight.js/lib/languages/r";
import ruby from "highlight.js/lib/languages/ruby";
import rust from "highlight.js/lib/languages/rust";
import scss from "highlight.js/lib/languages/scss";
import shell from "highlight.js/lib/languages/shell";
import sql from "highlight.js/lib/languages/sql";
import swift from "highlight.js/lib/languages/swift";
import typescript from "highlight.js/lib/languages/typescript";
import vbnet from "highlight.js/lib/languages/vbnet";
import wasm from "highlight.js/lib/languages/wasm";
import html from "highlight.js/lib/languages/xml";
import yaml from "highlight.js/lib/languages/yaml";
import { createLowlight } from "lowlight";

const lowlight = createLowlight();

lowlight.register("None", plainText);
lowlight.register("bash", bash);
lowlight.register("c", c);
lowlight.register("cpp", cpp);
lowlight.register("csharp", csharp);
lowlight.register("css", css);
lowlight.register("dart", dart);
lowlight.register("diff", diff);
lowlight.register("go", go);
lowlight.register("graphql", graphql);
lowlight.register("ini", ini);
lowlight.register("java", java);
lowlight.register("javascript", javascript);
lowlight.register("json", json);
lowlight.register("kotlin", kotlin);
lowlight.register("less", less);
lowlight.register("lua", lua);
lowlight.register("makefile", makefile);
lowlight.register("html", html);
lowlight.register("markdown", markdown);
lowlight.register("objectivec", objectivec);
lowlight.register("perl", perl);
lowlight.register("php", php);
lowlight.register("python", python);
lowlight.register("r", r);
lowlight.register("ruby", ruby);
lowlight.register("rust", rust);
lowlight.register("scss", scss);
lowlight.register("shell", shell);
lowlight.register("sql", sql);
lowlight.register("swift", swift);
lowlight.register("typescript", typescript);
lowlight.register("vbnet", vbnet);
lowlight.register("wasm", wasm);
lowlight.register("yaml", yaml);

export default lowlight;